name: Generate Changelog
on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1.1
        with:
          token: ${{ secrets.AIDUDEZZ_BOT_TOKEN }}

      - name: Commit files
        env: 
          CI_USER: ${{ secrets.AIDUDEZZZ_BOT_USER }}
          CI_EMAIL: ${{ secrets.AIDUDEZZZ_BOT_EMAIL }}
        run: |
          git config --local user.email ${{ secrets.AIDUDEZZZ_BOT_EMAIL }}
          git config --local user.name ${{ secrets.AIDUDEZZZ_BOT_USER }}
          git add CHANGELOG.md && git commit -m 'Updated CHANGELOG.md' && echo ::set-env name=push::1 || echo "No changes to CHANGELOG.md"
      - name: Push changes
        if: env.push == 1
        env: 
          CI_USER: ${{ secrets.AIDUDEZZZ_BOT_USER }}
          CI_TOKEN: ${{ secrets.AIDUDEZZZ_BOT_TOKEN }}
        run: |
          git push "https://$CI_USER:$CI_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:dev